name: 'Push Monorepo Folder'
description: 'Pushes changes from a monorepo folder to a dedicated repository using git subtree split'
author: 'Lorenzo Dessimoni'

inputs:
  local:
    description: 'Local folder path to sync'
    required: true
  remote:
    description: 'Target repository URL (HTTPS or SSH format)'
    required: true
  branch:
    description: 'Branch name to push to (auto-detected if not provided)'
    required: false
    default: ''
  token:
    description: 'GitHub authentication token with push access'
    required: false
    default: ''
  author:
    description: 'Git author in format "Name <email>" (uses git config if not provided)'
    required: false
    default: ''

outputs:
  pushed:
    description: 'Boolean indicating if push occurred ("true" or "false")'
    value: ${{ steps.push.outputs.pushed }}
  skipped:
    description: 'Boolean indicating if skipped due to no changes ("true" or "false")'
    value: ${{ steps.push.outputs.skipped }}

runs:
  using: 'composite'
  steps:
    - name: Execute push script
      id: push
      shell: bash
      run: |
        ARGS=("${{ github.action_path }}/scripts/push.sh" "${{ inputs.local }}" "${{ inputs.remote }}")

        if [[ -n "${{ inputs.branch }}" ]]; then
          ARGS+=("--branch" "${{ inputs.branch }}")
        fi

        if [[ -n "${{ inputs.token }}" ]]; then
          ARGS+=("--token" "${{ inputs.token }}")
        fi

        if [[ -n "${{ inputs.author }}" ]]; then
          ARGS+=("--author" "${{ inputs.author }}")
        fi

        "${ARGS[@]}"

branding:
  icon: 'git-branch'
  color: 'blue'
